/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_2;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        double gc, gf, gk;
        Scanner obxScaner = new Scanner (System.in);
        System.out.println("Introducir temperratura en grados centigrados");
        gc=obxScaner.nextDouble();
        gf=gc*9/5+32;
        gk=273.15;
        System.out.println(+gc+ " grados centigrados" +(gc+gk)+ "grados kelvin y"+gf+"grados Farenheitt");
    }
}
